### ISSUE TITLE
HandleButtonIcon/HandleAssets.IconInfos assumes quest fish are only vanilla, which is not true

### ISSUE THREAD

**Issue by JavidPack** [Crapsky233/DialogueTweak#7]
Error reported from a user:

```cs
[19:57:52.801] [Main Thread/WARN] [tML]: Silently Caught Exception: 
ReLogic.Content.AssetLoadException: Asset could not be found: "Images\Item_6070"
   at ReLogic.Content.AssetRepository.LoadAssetWithPotentialAsync[T](Asset`1 asset, AssetRequestMode mode) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 276
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ReLogic.Content.AssetRepository.LoadAssetWithPotentialAsync[T](Asset`1 asset, AssetRequestMode mode)
   at ReLogic.Content.AssetRepository.LoadAsset[T](Asset`1 asset, AssetRequestMode mode) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 214
   at ReLogic.Content.AssetRepository.Request[T](String assetName, AssetRequestMode mode) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Content\AssetRepository.cs:line 143
   at Terraria.ModLoader.ModContent.Request[T](String name, AssetRequestMode mode) in tModLoader\Terraria\ModLoader\ModContent.cs:line 114
   at DialogueTweak.Interfaces.ChatMethods.HandleButtonIcon(Int32 i, Asset`1& shop, Rectangle& shopFrame, Func`1& shopCustomOffset, Asset`1& extra, Rectangle& extraFrame, Func`1& extraCustomOffset) in DialogueTweak\Interfaces\ChatMethods.cs:line 177
   at DialogueTweak.Interfaces.ButtonHandler.DrawButtons(Int32 statY, String focusText, String focusText2) in DialogueTweak\Interfaces\ButtonHandler.cs:line 72
   at DialogueTweak.Interfaces.ChatUI.DrawButtons(String focusText, String focusText2, Single linePositioning) in DialogueTweak\Interfaces\ChatUI.cs:line 122
   at DialogueTweak.Interfaces.ChatUI.Draw(SpriteBatch spriteBatch) in DialogueTweak\Interfaces\ChatUI.cs:line 75
   at DialogueTweak.DialogueTweakSystem.<ModifyInterfaceLayers>b__9_2() in DialogueTweakSystem.cs:line 75
   at Terraria.UI.GameInterfaceLayer.Draw() in tModLoader\Terraria\UI\GameInterfaceLayer.cs:line 25
   at Terraria.Main.DrawInterface(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 38074
   at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Terraria.Main.Draw_Inner(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()
```

Some other relevant code:
https://github.com/Cyrillya/DialogueTweak/blob/2e7f8b35235a86dc757b0c12da3595647236b64d/HandleAssets.cs#L23-L28

Looks like this code is assuming all quest fish are vanilla items, this is not true. It would probably better to use TextureAssets.Item somehow.

**Comment by Cyrillya** [comment]
Fixed in https://github.com/Cyrillya/DialogueTweak/commit/8be3b19c749919ea2526f16be0448e04d3d37a37

![image](https://github.com/Cyrillya/DialogueTweak/assets/35227653/bdd20dfc-fe9c-4ded-924c-38d81f8237cf)
